export const YoutubeAPIKey="AIzaSyAqrNT30zUZprDAT5YoDqI89Rw4VI8ZBnA"
export const instanceLocator="v1:us1:bb7f0f6e-8aa3-48eb-b05c-88ca7cee073f"
export const tokenUrl="https://us1.pusherplatform.io/services/chatkit_token_provider/v1/bb7f0f6e-8aa3-48eb-b05c-88ca7cee073f/token"
export const cloudinaryUrl = "	https://api.cloudinary.com/v1_1/dfosmeuuq/upload"
export const cloudinaryUploadPreset = "m7uxkar3"
export const backendEndpoint = "https://snowhubbackend.herokuapp.com/api/v1"
